mqtt:
    host: 10.0.0.210
    port: 1883
    client: kamstrup
    topic: kamstrup
    qos: 0
    retain: False
    authentication: False
    username: user1
    password: changeit
serial_device:
    com_port: /dev/ttyKamstrup
kamstrup:
    parameters:
    - energy
    - volume
    - temp1
    - temp2
    poll_interval: 28
